# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='nombre_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='nombre_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='nombre_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
