# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_album_caratula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='caratula',
        ),
    ]
