# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='nombre_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
