# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_playlist_nombre_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='caciones',
            new_name='canciones',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
