# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20170107_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='canciones',
            new_name='caciones',
        ),
    ]
